# Generated by Django 4.1 on 2022-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('description', models.TextField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
